### ISSUE TITLE
span.Click() not working

### ISSUE THREAD

**Issue by mike-maina** [neworld/spanner#4]
Spanner spanner = new Spanner()
                .append("I accept terms & conditions")

                
                .span("terms & conditions", Spans.click(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        startActivity(new Intent(ConfirmOtpActivity.this, TermsAndConditionActivity.class));
                        Log.e("testing", "testing");
                    }
                }));
 txt_terms_and_condition.setText(spanner);

my gradle 
 compileSdkVersion 26
    buildToolsVersion '26.0.2'
    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 26}
am testing with android 6 device

![screenshot](https://user-images.githubusercontent.com/16883677/32878697-2cea46b8-cab8-11e7-80f3-78d35a6f9658.jpeg)

**Comment by neworld** [comment]
Hello @mike-maina,

Did you setup movement method of that `TextView`?

```
textView.setMovementMethod(new LinkMovementMethod());
```

**Comment by mike-maina** [comment]
unfortunately i had not done so (textView.setMovementMethod(new LinkMovementMethod());) even after spending a few hours trying to figure out what was going wrong.

Thank you for your time. It worked after adding that line of code.

**Comment by neworld** [comment]
Glad it worked for you. I will clarify documentation about this. Maybe, do you have an idea how it could be solved gracefully with lib API?
